vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end

local M = {}

local p = {
    transparent = "none",
    accent = "#c9a5b5",
    secondary = "#bdb2e0",
    muted = "#d4b5a0",
    fg = "#c9c7cd",
    dimmed = "#7b7b80",
    separator = "#353539",
}

local function hl(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

vim.cmd([[highlight StatusLine guibg=NONE]])

hl("Normal", { bg = p.transparent, ctermbg = p.transparent })
hl("NormalNC", { bg = p.transparent, ctermbg = p.transparent })
hl("TelescopeBorder", { bg = p.transparent, fg = p.dimmed })
hl("NormalFloat", { bg = p.transparent, fg = p.transparent })
hl("FloatBorder", { bg = p.transparent, fg = p.dimmed })
hl("Pmenu", { bg = p.transparent, fg = p.dimmed })
hl("PmenuSel", { bg = p.transparent, fg = p.secondary })
hl("PmenuThumb", { bg = p.dimmed, fg = p.dimmed })
hl("PmenuSbar", { bg = p.dimmed, fg = p.dimmed })
hl("@lsp.type.struct", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.keyword", { bg = p.transparent, fg = p.accent })
hl("@lsp.type.string", { bg = p.transparent, fg = p.muted })
hl("@lsp.type.method", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.function", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.function.swift", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.decorator", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.modifier", { bg = p.transparent, fg = p.secondary })
hl("@variable", { bg = p.transparent, fg = p.fg })
hl("@variable.member", { bg = p.transparent, fg = p.fg })
hl("@variable.parameter", { bg = p.transparent, fg = p.fg })
hl("@type.swift", { bg = p.transparent, fg = p.secondary })
hl("Type", { bg = p.transparent, fg = p.secondary })
hl("@type.definition", { bg = p.transparent, fg = p.secondary })
hl("@keyword.type", { bg = p.transparent, fg = p.accent })
hl("@keyword.modifier", { bg = p.transparent, fg = p.accent })
hl("@variable.builtin", { bg = p.transparent, fg = p.accent })
hl("@keyword", { bg = p.transparent, fg = p.accent })
hl("@attribute", { bg = p.transparent, fg = p.secondary })
hl("@string", { bg = p.transparent, fg = p.muted })
hl("@constructor", { bg = p.transparent, fg = p.accent })
hl("@function.method", { bg = p.transparent, fg = p.secondary })
hl("Function", { bg = p.transparent, fg = p.secondary })
hl("@function.call", { bg = p.transparent, fg = p.secondary })
hl("SnippetTabStop", { bg = p.transparent, fg = p.transparent })
hl("DiagnosticUnnecessary", { bg = p.transparent, fg = p.transparent })
hl("@lsp.type.function.swift", { bg = p.transparent, fg = p.fg })
hl("@punctuation.bracket.lua", { bg = p.transparent, fg = p.fg })
hl("@constructor.lua", { bg = p.transparent, fg = p.fg })
hl("Constant", { bg = p.transparent, fg = p.muted })
hl("String", { bg = p.transparent, fg = p.muted })
hl("Identifier", { bg = p.transparent, fg = p.fg })
hl("Special", { bg = p.transparent, fg = p.secondary })
hl("@number", { bg = p.transparent, fg = p.muted })
hl("@number.lua", { bg = p.transparent, fg = p.muted })
hl("@lsp.typemod.property.defaultLibrary.swift", { bg = p.transparent, fg = p.accent })
hl("@lsp.typemod.method.defaultLibrary.swift", { bg = p.transparent, fg = p.accent })
hl("@lsp.typemod.function.defaultLibrary.swift", { bg = p.transparent, fg = p.accent })
hl("@lsp.typemod.method.static.swift", { bg = p.transparent, fg = p.secondary })
hl("@lsp.mod.property.static.swift", { bg = p.transparent, fg = p.fg })
hl("@lsp.type.property", { bg = p.transparent, fg = p.fg })
hl("@lsp.type.class.swift", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.struct.swift", { bg = p.transparent, fg = p.secondary })
hl("@keyword.conditional.ternary.swift", { bg = p.transparent, fg = p.fg })
hl("@punctuation.special.swift", { bg = p.transparent, fg = p.fg })
hl("@function.macro.swift", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.enumMember.swift", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.enum.rust", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.enumMember.rust", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.macro.rust", { bg = p.transparent, fg = p.accent })
hl("@lsp.type.lifetime.rust", { bg = p.transparent, fg = p.muted })
hl("@lsp.type.builtinType.rust", { bg = p.transparent, fg = p.accent })
hl("@lsp.type.interface.rust", { bg = p.transparent, fg = p.secondary })
hl("@lsp.type.typeParameter.rust", { bg = p.transparent, fg = p.muted })
hl("@lsp.typemod.function.unsafe.rust", { bg = p.transparent, fg = p.secondary, italic = true })
hl("@lsp.type.comment.rust", { bg = p.transparent, fg = p.dimmed })
hl("DiagnosticUnderlineError", { undercurl = true, sp = p.accent })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.muted })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.secondary })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.muted })
hl("BlinkCmpMenuSelection", { bg = p.transparent, fg = p.fg })
hl("CursorLine", { bg = p.transparent, fg = p.transparent })
hl("netrwdir", { bg = p.transparent, fg = p.secondary })
hl("DiagnosticVirtualTextInfo", { bg = p.transparent, fg = p.secondary })
hl("Directory", { bg = p.transparent, fg = p.secondary })
hl("SnacksWinSeparator", { bg = p.transparent, fg = p.transparent, sp = p.transparent })
hl("SnacksPickerIconMethod", { bg = p.transparent, fg = p.fg, sp = p.transparent })
hl("SnacksPickerMatch", { bg = p.transparent, fg = p.fg })
hl("SnacksPickerDirectory", { bg = p.transparent, fg = p.fg })
hl("SnacksPickerFile", { bg = p.transparent, fg = p.dimmed })
hl("SnacksPickerInputSearch", { bg = p.transparent, fg = p.fg })
hl("SnacksPickerBoxBorder", { bg = p.transparent, fg = p.dimmed })
hl("SnacksPickerListBorder", { bg = p.transparent, fg = p.dimmed })
hl("SnacksPickerInputBorder", { bg = p.transparent, fg = p.dimmed })
hl("LspInlayHint", { bg = p.transparent, fg = p.dimmed })
hl("SnacksPickerBorder", { bg = p.transparent, fg = p.dimmed })
hl("DiffChange", { bg = p.transparent, fg = p.transparent })
hl("DiffDelete", { bg = "#2a1f1f", fg = p.transparent })
hl("DiffText", { bg = "#1f2a1f", fg = p.transparent })
hl("DiffAdd", { bg = "#1f2a1f", fg = p.transparent })
hl("WinSeparator", { bg = p.transparent, fg = p.separator })
hl("SnacksPickerPreviewBorder", { bg = p.transparent, fg = p.dimmed })
hl("Substitute", { bg = p.accent, fg = p.separator })
hl("ColorColumn", { bg = p.transparent })
hl("RenderMarkdownH2Bg", { link = "Normal" })
hl("RenderMarkdownH1Bg", { link = "Normal" })
hl("RenderMarkdownH3Bg", { link = "Normal" })
hl("RenderMarkdownH4Bg", { link = "Normal" })
hl("RenderMarkdownH5Bg", { link = "Normal" })
hl("RenderMarkdownH6Bg", { link = "Normal" })
hl("CodeCompanionInlineDiffHint", { bg = p.transparent })
hl("TermCursor", { bg = p.accent })
hl("Visual", { bg = p.separator })
hl("Search", { bg = p.separator, fg = p.muted })
hl("IncSearch", { bg = p.accent, fg = p.separator })
hl("CurSearch", { bg = p.accent, fg = p.separator })
hl("LineNr", { bg = p.transparent, fg = p.separator })
hl("CursorLineNr", { bg = p.transparent, fg = p.dimmed })
hl("SignColumn", { bg = p.transparent })
hl("FoldColumn", { bg = p.transparent, fg = p.separator })
hl("Folded", { bg = p.transparent, fg = p.dimmed })
hl("MatchParen", { bg = p.separator, fg = p.fg, bold = true })
hl("NonText", { bg = p.transparent, fg = p.separator })
hl("EndOfBuffer", { bg = p.transparent, fg = p.transparent })
hl("Whitespace", { bg = p.transparent, fg = p.separator })
hl("Title", { bg = p.transparent, fg = p.accent, bold = true })
hl("ErrorMsg", { bg = p.transparent, fg = p.accent })
hl("WarningMsg", { bg = p.transparent, fg = p.muted })
hl("Todo", { bg = p.transparent, fg = p.accent, bold = true })
hl("DiagnosticError", { bg = p.transparent, fg = p.accent })
hl("DiagnosticWarn", { bg = p.transparent, fg = p.muted })
hl("DiagnosticHint", { bg = p.transparent, fg = p.dimmed })
hl("DiagnosticInfo", { bg = p.transparent, fg = p.secondary })
hl("@comment", { bg = p.transparent, fg = p.dimmed })
hl("@boolean", { bg = p.transparent, fg = p.muted })
hl("@operator", { bg = p.transparent, fg = p.fg })
hl("@punctuation", { bg = p.transparent, fg = p.fg })
hl("@punctuation.bracket", { bg = p.transparent, fg = p.fg })
hl("@punctuation.delimiter", { bg = p.transparent, fg = p.fg })
hl("@punctuation.special", { bg = p.transparent, fg = p.accent })
hl("@property", { bg = p.transparent, fg = p.secondary })
hl("@label", { bg = p.transparent, fg = p.secondary })
hl("@tag", { bg = p.transparent, fg = p.accent })
hl("@tag.attribute", { bg = p.transparent, fg = p.secondary })
hl("@tag.delimiter", { bg = p.transparent, fg = p.fg })
hl("@type", { bg = p.transparent, fg = p.secondary })
hl("@type.builtin", { bg = p.transparent, fg = p.secondary })
hl("@module", { bg = p.transparent, fg = p.fg })
hl("@string.escape", { bg = p.transparent, fg = p.accent })
hl("@string.special", { bg = p.transparent, fg = p.muted })
hl("@string.special.url", { bg = p.transparent, fg = p.secondary, underline = true })
hl("@constant.builtin", { bg = p.transparent, fg = p.accent })
hl("@function.builtin", { bg = p.transparent, fg = p.secondary })
hl("@markup.heading", { bg = p.transparent, fg = p.accent, bold = true })
hl("@markup.bold", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.link", { bg = p.transparent, fg = p.secondary, underline = true })
hl("@markup.raw", { bg = p.transparent, fg = p.muted })
hl("@markup.list", { bg = p.transparent, fg = p.accent })
hl("@keyword.vim", { bg = p.transparent, fg = p.accent })
hl("@function.call.vim", { bg = p.transparent, fg = p.secondary })
hl("@function.macro.vim", { bg = p.transparent, fg = p.secondary })
hl("@string.vim", { bg = p.transparent, fg = p.muted })
hl("@number.vim", { bg = p.transparent, fg = p.muted })
hl("@variable.vim", { bg = p.transparent, fg = p.fg })
hl("@variable.builtin.vim", { bg = p.transparent, fg = p.accent })
hl("@type.vim", { bg = p.transparent, fg = p.secondary })
hl("@operator.vim", { bg = p.transparent, fg = p.fg })
hl("@string.special.path.vim", { bg = p.transparent, fg = p.muted })
hl("@module.vim", { bg = p.transparent, fg = p.dimmed })
hl("@comment.vim", { bg = p.transparent, fg = p.dimmed })

-- review/agent inline markers — bright so they pop over dimmed comments
hl("ReviewMarker", { fg = p.muted, bold = true })
hl("AgentMarker", { fg = p.muted, bold = true })
hl("ReviewLine", { fg = p.fg })
hl("AgentLine", { fg = p.fg })

vim.api.nvim_create_autocmd({ "BufReadPost", "BufNewFile" }, {
    callback = function()
        vim.fn.matchadd("ReviewLine", "\\v.*<review:.*", 10)
        vim.fn.matchadd("AgentLine", "\\v.*<agent:.*", 10)
        vim.fn.matchadd("ReviewMarker", "\\v<review:", 11)
        vim.fn.matchadd("AgentMarker", "\\v<agent:", 11)
    end,
})

M.palette = p
return M
