vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

local p = {
	none = "none",
	cyan = "NvimLightBlue",
	dark_purple = "#c3a6f8",
	green = "#a1c5bc",
	grey = "#9b9ea4",
	info_blue = "#5fafff",
	orange = "#dd977f",
	pink = "#dd93b6",
	purple = "#dfd1fb",
	warn_orange = "#ffaf00",
	white = "#ffffff",
	yellow = "#cfc877",
}

local function hl(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

vim.cmd([[highlight StatusLine guibg=NONE]])

hl("Normal", { bg = "none", ctermbg = "none" })
hl("NormalNC", { bg = "none", ctermbg = "none" })
hl("TelescopeBorder", { bg = "none", fg = p.grey })
hl("NormalFloat", { bg = "none", fg = "none" })
hl("FloatBorder", { bg = "none", fg = p.grey })
hl("Pmenu", { bg = "none", fg = p.grey })
hl("PmenuSel", { bg = "none", fg = p.cyan })
hl("PmenuThumb", { bg = p.grey, fg = p.grey })
hl("PmenuSbar", { bg = p.grey, fg = p.grey })
hl("@lsp.type.struct", { bg = "none", fg = p.purple })
hl("@lsp.type", { bg = "none", fg = p.cyan })
hl("@lsp.type.keyword", { bg = "none", fg = p.pink })
hl("@lsp.type.string", { bg = "none", fg = p.orange })
hl("@lsp.type.method", { bg = "none", fg = p.cyan })
hl("@lsp.type.function", { bg = "none", fg = p.green })
hl("@lsp.type.function.swift", { bg = "none", fg = p.green })
hl("@lsp.type.decorator", { bg = "none", fg = p.purple })
hl("@lsp.type.modifier", { bg = p.none, fg = p.purple })
hl("@variable", { bg = p.none, fg = p.white })
hl("@variable.member", { bg = p.none, fg = p.white })
hl("@variable.parameter", { bg = p.none, fg = p.white })
hl("@type.swift", { bg = p.none, fg = p.purple })
hl("Type", { bg = p.none, fg = p.purple })
hl("@type.definition", { bg = p.none, fg = p.purple })
hl("@keyword.type", { bg = p.none, fg = p.pink })
hl("@keyword.modifier", { bg = p.none, fg = p.pink })
hl("@variable.builtin", { bg = p.none, fg = p.pink })
hl("@keyword", { bg = p.none, fg = p.pink })
hl("@attribute", { bg = p.none, fg = p.purple })
hl("@string", { bg = p.none, fg = p.orange })
hl("@constructor", { bg = p.none, fg = p.pink })
hl("@function.method", { bg = p.none, fg = p.cyan })
hl("Function", { bg = p.none, fg = p.cyan })
hl("@function.call", { bg = p.none, fg = p.green })
hl("SnippetTabStop", { bg = p.none, fg = p.none })
hl("DiagnosticUnnecessary", { bg = p.none, fg = p.none })
hl("@lsp.type.function.swift", { bg = p.none, fg = p.white })
hl("@punctuation.bracket.lua", { bg = p.none, fg = p.white })
hl("@constructor.lua", { bg = p.none, fg = p.white })
hl("Constant", { bg = p.none, fg = p.pink })
hl("Special", { bg = p.none, fg = p.purple })
hl("@number", { bg = p.none, fg = p.yellow })
hl("@number.lua", { bg = p.none, fg = p.yellow })
hl("@lsp.typemod.property.defaultLibrary.swift", { bg = p.none, fg = p.dark_purple })
hl("@lsp.typemod.method.defaultLibrary.swift", { bg = p.none, fg = p.dark_purple })
hl("@lsp.typemod.function.defaultLibrary.swift", { bg = p.none, fg = p.dark_purple })
hl("@lsp.typemod.method.static.swift", { bg = p.none, fg = p.green })
hl("@lsp.mod.property.static.swift", { bg = p.none, fg = p.white })
hl("@lsp.type.property.swift", { bg = p.none, fg = p.green })
hl("@lsp.type.class.swift", { bg = p.none, fg = p.purple })
hl("@lsp.type.struct.swift", { bg = p.none, fg = p.purple })
hl("@keyword.conditional.ternary.swift", { bg = p.none, fg = p.white })
hl("@punctuation.special.swift", { bg = p.none, fg = p.white })
hl("@function.macro.swift", { bg = p.none, fg = p.purple })
hl("@lsp.type.enumMember.swift", { bg = p.none, fg = p.green })
hl("DiagnosticUnderlineError", { undercurl = true, sp = "NvimLightRed" })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.warn_orange })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.info_blue })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.yellow })
hl("BlinkCmpMenuSelection", { bg = p.none, fg = p.white })
hl("CursorLine", { bg = p.none, fg = p.none })
hl("netrwdir", { bg = p.none, fg = p.cyan })
hl("DiagnosticVirtualTextInfo", { bg = p.none, fg = p.cyan })
hl("Directory", { bg = p.none, fg = p.cyan })
hl("WinSeparator", { bg = p.none, fg = p.none, sp = p.none })
hl("SnacksWinSeparator", { bg = p.none, fg = p.none, sp = p.none })
hl("SnacksPickerIconMethod", { bg = p.none, fg = p.white, sp = p.none })
hl("SnacksPickerMatch", { bg = p.none, fg = p.white })
hl("SnacksPickerDirectory", { bg = p.none, fg = p.white })
hl("SnacksPickerFile", { bg = p.none, fg = p.grey })
hl("SnacksPickerInputSearch", { bg = p.none, fg = p.white })
hl("SnacksPickerBoxBorder", { bg = p.none, fg = p.grey })
hl("SnacksPickerListBorder", { bg = p.none, fg = p.grey })
hl("SnacksPickerInputBorder", { bg = p.none, fg = p.grey })
hl("SnacksPickerBorder", { bg = p.none, fg = p.grey })
hl("SnacksPickerPreviewBorder", { bg = p.none, fg = p.grey })
hl("Substitute", { bg = p.dark_purple, fg = "NvimDarkGrey4" })
hl("ColorColumn", { bg = p.none })
hl("DiffAdd", { fg = p.none })
hl("RenderMarkdownH2Bg", { link = "Normal" })
hl("RenderMarkdownH1Bg", { link = "Normal" })
hl("RenderMarkdownH3Bg", { link = "Normal" })
hl("RenderMarkdownH4Bg", { link = "Normal" })
hl("RenderMarkdownH5Bg", { link = "Normal" })
hl("RenderMarkdownH6Bg", { link = "Normal" })
hl("CodeCompanionInlineDiffHint", { bg = p.none })
