font_size 15.0
enable_audio_bell no
resize_debounce_time 0.0
repaint_delay 1
input_delay 1
shell_integration fish
allow_remote_control yes
touch_scroll_multiplier 5.0
mouse_hide_wait -0.1
copy_on_select no
tab_bar_min_tabs 2
tab_title_template "{fmt.fg.tab}{index}:{title}"
tab_bar_align right
macos_menubar_title_max_length 0
macos_quit_when_last_window_closed yes

map ctrl+1 send_text all \x1b[49;5u
map ctrl+2 send_text all \x1b[50;5u
map ctrl+3 send_text all \x1b[51;5u
map ctrl+4 send_text all \x1b[52;5u
map ctrl+5 send_text all \x1b[53;5u
map shift+enter send_text all \x1b[13;2u

foreground               #c9c7cd
background               #161617
selection_foreground     #c9c7cd
selection_background     #353539

cursor                   #c9c7cd
cursor_text_color        #161617
cursor_shape             beam
cursor_blink_interval    0

url_color                #bdb2e0

active_tab_foreground    #c9c7cd
active_tab_background    #161617
inactive_tab_foreground  #353539
inactive_tab_background  #161617
active_tab_font_style   normal
inactive_tab_font_style normal

# black
color0   #27272a
color8   #353539

# red
color1   #d4b5a0
color9   #dfc2ad

# green
color2   #c9a5b5
color10  #d4b0c0

# yellow
color3   #d4b5a0
color11  #dfc2ad

# blue
color4   #bdb2e0
color12  #c8bee8

# magenta
color5   #c9a5b5
color13  #d4b0c0

# cyan
color6   #bdb2e0
color14  #c8bee8

# white
color7   #c9c7cd
color15  #d4d2d8

confirm_os_window_close 0
macos_option_as_alt yes

allow_remote_control yes
listen_on unix:/tmp/kitty

window_padding_width 2 0 0 0
modify_font cell_height 150%
tab_bar_margin_width 10
tab_bar_style separator
scrollbar scrolled
tab_separator '  '


font_family      family="Fira Code"
bold_font        auto
italic_font      auto
bold_italic_font auto
