return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	lazy = true,
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").install({
			"c",
			"objc",
			"cpp",
			"go",
			"lua",
			"zig",
			"python",
			"rust",
			"tsx",
			"nix",
			"typescript",
			"vimdoc",
			"vim",
			"javascript",
			"json",
			"regex",
			"bash",
			"markdown",
			"markdown_inline",
			"yaml",
			"swift",
		})
	end,
}
