[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 10000

[font]
size = 16.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

[font.offset]
y = 24

[cursor]
style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[colors.selection]
background = "#353539"
text = "#c9c7cd"

[colors.cursor]
cursor = "#c9c7cd"
text = "#161617"

[colors.normal]
black = "#27272a"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#ea83a5"
white = "#c1c0d4"

[colors.bright]
black = "#353539"
red = "#ffae9f"
green = "#9dc6ac"
yellow = "#f0c5a9"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#f591b2"
white = "#cac9dd"
