add_newline = false

format = """
$directory\
$jobs\
$character\
"""

[directory]
format = "[$path]($style) "
style = "#bdb2e0"
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
disabled = true

[character]
disabled = false
success_symbol = '[❯](#bdb2e0)'
error_symbol = '[❯](#d4b5a0)'

[jobs]
symbol = ''
style = 'bold #d4b5a0'
