add_newline = false

format = """
$directory\
$jobs\
$character\
"""

[directory]
format = "[$path]($style) "
style = "#aca1cf"
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
disabled = true

[character]
disabled = false
success_symbol = '[❯](#aca1cf)'
error_symbol = '[❯](#f5a191)'

[jobs]
symbol = ''
style = 'bold #f5a191'
